{% set name = "serotyperextras" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../serotyperextras

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools >=61
    - wheel
  run:
    - python >=3.10
    - biopython
    - numba

test:
  imports:
    - serotyperextras
  commands:
    - python -c "import serotyperextras; print('import OK')"
    - annotate --help
    - fastaga --help

about:
  home: https://github.com/Rohit-Satyam/serotyperextras
  summary: Extra Python utilities for serotyping
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Rohit-Satyam
